### PR TITLE
Page editor

### PR DESCRIPTION
**Pull request by andrei-markeev**
Adds a tab which displays list of webparts and allows editing them (as XML). This is a basic version that can be extended later.

screenshot

### CODE REVIEW

**Comment by tavikukko** [comment]
Greate job @andrei-markeev !! Im little busy now, but will check this out more deeply in the beginning of next week.

**Comment by andrei-markeev** [comment]
Sure, no rush!

Some more ideas for how this page editor can be extended (putting here so I don't forget):
1. Adding and deleting webparts
2. Drag-n-drop: ordering of the webparts and moving them between webpart zones
3. Specialized editors for certain types of OOTB webparts
4. Possibility to edit the page layout
5. Smart preview - so when you update webpart, it updates on page without need of full page reload

**Comment by Danny-Engelman** [comment]
You two are in another league, way cool, as always.

I have been using Monaco to edit HTML & JS files in SharePoint Libraries since september.

By default SharePoints opens js files as text, and downloads HTML files,
but you can open them with the correct Monaco URL

I now use Cisar to add the correct Monaco URL in the View so users can open those files (benefit works in all browsers)
I posted the CSR code at: https://github.com/SharePoint/sp-dev-fx-webparts/issues/153


For quick access/edit would be great if SP/Page Editor could edit these files

**Comment by tavikukko** [comment]
Thanks @Danny-Engelman !
The use of monaco-editor in the project opens up a lot of possibilities.
Here are some ideas that I will start working, when I got the time :)
- Extending Page editor
- Lists RootFolder property editor
- Editing files / pagelayouts / masterpages with monaco-editor

**Comment by Danny-Engelman** [comment]
Personally I am on the [WebComponents.org](http://WebComponents.org) track and less on the React track Microsoft is taking (some would say pushing)

WebComponents are conceptually no different than the CEWP customizations we have done for years.

Since I discovered Monaco; I keep saying: It is the CEWP on steriods

Someone reported to me today that JS files now open in Monaco in the New Experiences,  
haven't had time to test it

I will try and make some time and dive into your code

**Pull request merged**
