### PR TITLE
make it look like chrome developer tools

### PR DESCRIPTION
**Pull request by alirobe**
Hey, 

I've put CSS variables in place, and made it look like a chrome extension. What do you think? :)

### CODE REVIEW

**Comment by tavikukko** [comment]
Hi @alirobe and thanks for the PR!
It really look good, but maybe it looks "too" good and close to SharePoint Designer.. So I was thinking to have a switch to select the Theme of preference, but the thats not trivial. The editor that SP Editor is using is [monaco-editor](https://github.com/Microsoft/monaco-editor) and it is initialised once, which means that to change theme "on-the-fly" would need quite much refactoring. So, its either way, light or black, no switches. So I need to try this out and **maybe** I do a release and decide from the feedback if it was good or not, what do you think?

**Comment by alirobe** [comment]
How about storing the setting in localStorage and simply refreshing the page when it changes?

**Comment by tavikukko** [comment]
I tested the light theme. Personally I like the "dark side". There was some issues in UI.
- Files + Web Properties + List Properties, Web Hooks --> the textbox and button borders not aligned
- Site Designs --> not scrolling

**Comment by alirobe** [comment]
@tavikukko I've put it back in dark mode. I have a preference of staying the same as the rest of chrome dev tools, but all g. re-arranged & simplified CSS doc quite a bit so I could figure out what was going on, and fixed reported bugs.

**Comment by alirobe** [comment]
I could probably put a switch in for light/dark mode without much difficulty...

**Comment by tavikukko** [comment]
@alirobe go for it, helps my day :)

**Comment by alirobe** [comment]
Sorry! I've had family visiting. Still on my radar. I'll get on this soon.

**Comment by tavikukko** [comment]
No worries @alirobe , I've been busy too. Take your time.

**Comment by tavikukko** [comment]
SP Editor v6 will have dark/light modes. closing this, thanks for your contribution!

**Pull request closed without merging**
