### PR TITLE
Added validation for webhook ClientState and URL.

### PR DESCRIPTION
**Pull request by thomyg**
Added validations for the webhook panel.

- check for ClientState to be present.
- check for webhook URL to be present and match a URL regex.

If validation fails function returns and an error message is shown to the user.

### CODE REVIEW

**Comment by tavikukko** [comment]
Hi @thomyg !
The original problem was that, if the **clientState** parameter was left empty/null, PnPjs will default to "pnp-js-core-subscription". So, there was no option to leave it empty/null. So I made a PR to PnPjs to remove the default value. The PR got merged and it will be part of PnPjs in the next release 1.2.8.

**Comment by thomyg** [comment]
Understood.

Another thing: we realized that there is a size limit of the client state.

What about a check in SP editor on the length of the client state?

Could add this next week, if you approve the idea.

Would immediately provide feedback to the user instead of calling SharePoint and raising the specific exception.

--
sent from a magical device that lives in my pocket. please excuse typos.

Am 20.12.2018 um 21:35 schrieb Tomi Tavela <notifications@github.com<mailto:notifications@github.com>>:


Hi @thomyg<https://github.com/thomyg> !
The original problem was that, if the clientState parameter was left empty/null, PnPjs will default to "pnp-js-core-subscription". So, there was no option to leave it empty/null. So I made a PR to PnPjs to remove the default value. The PR got merged and it will be part of PnPjs in the next release 1.2.8.

**Comment by tavikukko** [comment]
ooh, didn't know about the max length. I think easiest is to add  maxlength="" attribute to the input field.

**Comment by thomyg** [comment]
Working on it ...

--
sent from a magical device that lives in my pocket. please excuse typos.

Am 20.12.2018 um 22:52 schrieb Tomi Tavela <notifications@github.com<mailto:notifications@github.com>>:


ooh, didn't know about the max length. I think easiest is to add maxlength="" attribute to the input field.

**Comment by tavikukko** [comment]
Added clientstate max length to 80, other changes were not needed. Thanks @thomyg for spotting and working with this!

**Pull request closed without merging**
